image: registry.gitlab.com/legionarius/template/godot-docker:latest

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - deploy

variables:
  EXPORT_NAME: landlord

linux:
  stage: export
  script:
    - scons platform=linux target=release use_llvm=yes
    - mkdir -v -p build/linux
    - godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux
    expire_in: 2 days

windows:
  stage: export
  script:
    - scons platform=windows target=release
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
    expire_in: 2 days

mac:
  stage: export
  when: manual
  script:
    - scons platform=osx target=release
    - mkdir -v -p build/mac
    - godot -v --export "Mac OSX" build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac
    expire_in: 2 days
    
html5:
  stage: export
  script:
    - scons platform=javascript target=release
    - mkdir -v -p build/html5
    - godot -v --export "HTML5" build/html5/index.html
  artifacts:
    name: $EXPORT_NAME-web
    paths:
      - build/html5
    expire_in: 2 days
    
# Itch.io Deploy
itchio:linux:
  stage: deploy
  only:
    - develop
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
  dependencies:
    - linux

itchio:windows:
  stage: deploy
  only:
    - develop
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
  dependencies:
    - windows

itchio:macosx:
  stage: deploy
  only:
    - develop
  script:
    - butler push ./build/mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac
  dependencies:
    - mac
