image: registry.gitlab.com/legionarius/template/godot-docker:latest

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - deploy

variables:
  EXPORT_NAME: godot-native
  GODOT_CPP: /home/root/godot-cpp/

linux:
  stage: export
  script:
    - scons platform=linux target=release
    - sed -i -e 's/X11.64/Server/g' lib/gdlibrary.tres
    - mkdir -v -p build/linux
    - godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - scons platform=windows target=release
    - sed -i -e 's/Windows.64/Server/g' lib/gdlibrary.tres
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

mac:
  stage: export
  when: manual
  script:
    - scons platform=osx target=release
    - mkdir -v -p build/mac
    - godot -v --export "Mac OSX" build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac

# Itch.io Deploy
itchio:linux:
  stage: deploy
  only:
    - develop
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
  dependencies:
    - linux

itchio:windows:
  stage: deploy
  only:
    - develop
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
  dependencies:
    - windows

itchio:macosx:
  stage: deploy
  only:
    - develop
  script:
    - butler push ./build/mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac
  dependencies:
    - mac
